---
- name: Script Load
  set_fact: 
     cmdArray: "{{ buildBaseDir}}/bin/ImportScript.sh "
  no_log: true
  
- name: Artfactory absolute path is set
  set_fact:
     artifactoryAbsoluteUrl: "{{artifactoryUrl}}{{artifactName}}"
  no_log: true
- name: ZipFileName is set
  set_fact:
     zipFileName: "{{buildBaseDir}}/zipDir/{{artifactName}}"
- name: Remote log directory set
  set_fact:
     logFileLoc: "{{ buildBaseDir }}/logs"
     
- name: Variable are load
  set_fact: 
     cmdArray: " {{cmdArray}} -{{ item }} {{ vars[item] }}" 
  when: not(
              (lookup('vars', item) is undefined)
              or
              (lookup('vars', item) is none)
              or 
              (lookup('vars', item) | trim == '')
          )

  loop:
    - bedrockUrl
    - logFileLoc 
    - userName
    - projectName
    - tarFileName
    - zipFileName
    - newRevision
    - updateAllConflicts 
    - timeout
  no_log: true
  
  
