---
- name: Import Artifact to ZDP1
  shell: "{{cmdArray}} -password '{{ zdp_password }}' "
  register: importLogs
  no_log: true
  
- name: LLL
  set_fact:
    out: importLogs.stdout_lines
 
- name: Import Artifact to ZDP
  shell: "{{cmdArray}} -password '{{ zdp_password }}' | tee {{buildBaseDir}}/log.txt"
  
- name: Debug Log
  shell: grep -o '[^ ]*\.txt' '{{ buildBaseDir }}'log.txt | tee '{{buildBaseDir}}'/newLogList.txt
  
#- name: Download the list of newly created log file
#  fetch: 
#    src: "{{buildBaseDir}}/newLogList.txt"
#    dest: "{{ansibleHome}}"
#    flat: yes

#- name: Dowload Logs for each tar
#  fetch:
#    src: "{{item}}"
#    dest: "{{ansibleHome}}/logs/"
#    flat: yes
#  with_lines: cat "{{ansibleHome}}/newLogList.txt"
