---
# vars file for ./roles/BOA_Role
newRevision: 
updateAllConflicts: 
timeout: 
bedrockUrl: 
#ansibleHome: 
buildBaseDir: 
logFileLoc: 

artifactoryAbsoluteUrl:

userName:  
projectName: 
tarFileName:   
zipFileName:

cmdArray: ' '
